nome = str(input("Qual é o seu nome? "))
nome = nome.lower()
print(f"A letra -A- aparece", nome.count("a"), "x no total.")
print(f"A letra -A- aparece pela primeira vez na posicao ", nome.find("a"[0:]))
print(f"A letra -A- aparece pela ultima vez em ", nome.find("a"[:50]))